### ISSUE TITLE
Create a multistep form to register adoption

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#125]
### Task
Let's recreate our old adoption register screen. This time, we want to split it into multiple screens in order to provide a better user experience. So for each field, we must have a dedicated screen and a "Next" button to advance to the next step. I suggest using [`react-hook-form`](https://react-hook-form.com/) to manage the form state and [`react-query`](https://tanstack.com/query/v4/?from=reactQueryV3&original=https://react-query-v3.tanstack.com/) for handling requests.

### Validation
We also want to improve the error feedback. Let's use a tooltip to show errors. The [snackbars ](https://callstack.github.io/react-native-paper/snackbar.html) should show up if the user tries to advance by clicking on the next button and the data typed on the field is not valid.

### Photos upload
Let's keep the same user experience allowing the user to upload up to 3 pictures.

### Endpoints
We already have the backend endpoints for basic crud ready to use.

**Create adoption** -> `POST api/v1/adoptions` 

### Tests
Please do not forget to add tests. I suggest [`react-testing-library`](https://testing-library.com/).

### Screenshots/Examples

| | | | | | | | | 
:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/19699724/199856690-5a7f2943-05ab-4f59-aeea-a81a3ec8b479.png) | ![image](https://user-images.githubusercontent.com/19699724/199856707-d09914a0-3613-4ced-a252-6616962ce5c2.png) | ![image](https://user-images.githubusercontent.com/19699724/199856918-3487f7e1-435a-4c03-af16-cc401c8d9a34.png) | ![image](https://user-images.githubusercontent.com/19699724/199856939-3f047930-db0f-4091-a2ca-0eec2c1e3f06.png) | ![image](https://user-images.githubusercontent.com/19699724/199856978-f915a0cd-9c72-4a45-a9fb-c2c2dfb7cd7a.png) | ![image](https://user-images.githubusercontent.com/19699724/199857048-7a6b30e5-83d6-4dfd-80ac-937838d61fa8.png) | ![image](https://user-images.githubusercontent.com/19699724/199857061-5b7000aa-9bf3-45a8-94b9-a2e791a2b15d.png) | ![image](https://user-images.githubusercontent.com/19699724/199857089-0ff47644-afac-4d44-8504-0f879e7ad98a.png)

**Comment by joaoGabriel55** [comment]
I can take this

**Comment by belgamo** [comment]
Please we haven't setup our design system yet. Use react-native-paper. Ping me on discord if you have any questions.

**Comment by belgamo** [comment]
Added more issues to finish this task:

https://github.com/animavita/animavita/issues/147
https://github.com/animavita/animavita/issues/148
https://github.com/animavita/animavita/issues/149
