### ISSUE TITLE
Manage my adoptions 

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#126]
depends on #125 

### Task 
Let's add the ability to edit, delete and view adoptions. The user must be able to see a list of [cards](https://callstack.github.io/react-native-paper/card-actions.html) and for that let's create a new [bottom tab](https://reactnavigation.org/docs/bottom-tab-navigator/). Each card is a registered adoption and should contain two buttons, one for the edition and another one to edit it. The [card](https://callstack.github.io/react-native-paper/card-actions.html) can also be clickable. 

### Endpoints
We already have the backend endpoints for basic crud ready to use.

**All adoption** -> `GET api/v1/adoptions` 
**Edit adoption** -> `PATCH api/v1/adoptions` (must include `id` in the body)
**Delete adoption** -> `DELETE api/v1/adoptions/:id` 

### Observations
Since we don't have the `user` module yet and the adoption doesn't belong to any user, let's use the all adoptions endpoint to list it.

**Comment by Cor4zon** [comment]
Hi @belgamo ! I would take that issue. Please assign it to me

**Comment by belgamo** [comment]
Hey @Cor4zon, assigned! Please be aware this issue depends on #125 which is in progress.

**Comment by Cor4zon** [comment]
@belgamo Does project have discord cannel or slack?

**Comment by belgamo** [comment]
Yes! https://discord.gg/Hf3R9erz

**Comment by belgamo** [comment]
Hey @Cor4zon not sure if you have already setup the project, but I updated the docs. Please let me know if you need any help 👊

**Comment by Cor4zon** [comment]
Nice! I had a bug, but now i solve it. Thanks for the nice docs.

**Comment by Cor4zon** [comment]
Waiting for https://github.com/animavita/animavita/pull/130 PR will be merged

**Comment by Cor4zon** [comment]
i see #125 task finished. Will do my task on weekend

**Comment by belgamo** [comment]
Hey really appreciate you're looking forward to helping us on this, but @joaoGabriel55 is still working on register adoptions, so you should wait until we move his ticket to done. Thanks :D

**Comment by belgamo** [comment]
Hey @Cor4zon feel free to start :)
