### ISSUE TITLE
Create user & auth module

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#128]
### Task
Let's add a module for our users. It's very self-explainable so here I'll just mention which fields it should contain:

- name
- email
- location (coordinates)
- photoUri

### [Authorization](https://docs.nestjs.com/security/authentication)
Let's add an authorization step where users can log in with their e-mail and password.

**Comment by JVBorges** [comment]
Can I take this one?

**Comment by belgamo** [comment]
> Can I take this one?

Please!

**Comment by JVBorges** [comment]
which strategy will be using for authentication?
