### ISSUE TITLE
Would like to join the project

### ISSUE THREAD

**Issue by The-Code-Monkey** [wendelfreitas/animavita#13]
Hi @wendelfreitas 

I would like to join the project if thats ok? 
Do we have some sort of centralised platform for communication E.G. Discord?
Is this for all animals or currently just Dogs/Cats? as i could bring some knowledge around reptiles, amphibians and arachnids too.
Also I feel like translations could be used for different languages as I see that the gifs are all in spanish?

What do you think?

Andy

**Comment by wendelfreitas** [comment]
Hello @The-Code-Monkey 

you can submit a PR for a feature, I'd love to see ...

the app caters to dogs / cats and others. I think the other cases will fall into the 'others' category

this in the project plans we put an internalization and that would be great.

thanks :hearts:
