### ISSUE TITLE
Improve UX on register adoptions steps

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#155]
We have a few issues when registering adoptions. The usability to navigate between the steps and to control the keyboard is not good.

<img width="338" alt="Screen Shot 2023-02-06 at 22 09 58" src="https://user-images.githubusercontent.com/19699724/217122388-55f353a4-af0f-42a9-b6e4-6da49b43d203.png">

As you can see, when the keyboard is opened the user can't navigate to the next step. To fix that, let's allow users to either close the keyboard by clicking outside or navigate to the next step by pressing the return key.

**Comment by faaiz99** [comment]
Hello, I would like to work on this issue :)

**Comment by faaiz99** [comment]
Hello, I would like to work on this issue.

**Comment by belgamo** [comment]
> Hello, I would like to work on this issue.

hey, go ahead! just assigned it to you

**Comment by belgamo** [comment]
@faaiz99 any update on this?

**Comment by faaiz99** [comment]
I will open PR this Sunday.

**Comment by faaiz99** [comment]
I'm having issues setting up the project. This seems like a complex project to set up. Please assign this issue to someone else. Thanks

**Comment by belgamo** [comment]
Hey @faaiz99 thanks for the feedback. I've been working hard to make this setup as simple as possible. Can you please provide more info like which OS you are using, whether you used docker, and what errors you got? Then I can see what we can do to improve even more.

**Comment by faaiz99** [comment]
@belgamo 

So I'm using windows 11 (22H2) with WSL2. I, Cloned the latest Build from the v2 branch. installed Docker using the docker-compose command. First I was confused between installing yarn or pnpm to install the dependencies. Also, the documentation needs to clarify the prerequisite accounts. First I need an AWS account then saw it wasn't needed if I'm using docker. I recommend mentioning at the start that MAC or Linux would be preferred and Contribution should be color coded!? Rest of the errors are wsl2 and I'm trying my best to start with this. 

I think this is the latest one. The difference is between builds. 
https://github.com/animavita/animavita/blob/next/CONTRIBUTION.md

This is the one that should work with this build. 
https://github.com/animavita/animavita/blob/v2/CONTRIBUTING.md 

What the installation procedure was
Install Docker, Make sure it is running
Clone the build
run pnpm install (for mobile dependencies)
run sudo docker-compose-up -d
run pnpm validation:build
run ngx expo start

**Comment by belgamo** [comment]
> @belgamo
> 
> So I'm using windows 11 (22H2) with WSL2. I, Cloned the latest Build from the v2 branch. installed Docker using the docker-compose command. First I was confused between installing yarn or pnpm to install the dependencies. Also, the documentation needs to clarify the prerequisite accounts. First I need an AWS account then saw it wasn't needed if I'm using docker. I recommend mentioning at the start that MAC or Linux would be preferred and Contribution should be color coded!? Rest of the errors are wsl2 and I'm trying my best to start with this.
> 
> I think this is the latest one. The difference is between builds. https://github.com/animavita/animavita/blob/next/CONTRIBUTION.md
> 
> This is the one that should work with this build. https://github.com/animavita/animavita/blob/v2/CONTRIBUTING.md
> 
> What the installation procedure was Install Docker, Make sure it is running Clone the build run pnpm install (for mobile dependencies) run sudo docker-compose-up -d run pnpm validation:build run ngx expo start

Thanks for the feedback.

First of all, I highly recommend you not use windows to develop react-native applications. You might run into several problems. 
Second, please do not use the master and next branches as a reference for anything, it's totally out of date so everything should be done under v2 branch (which I set as the default one).
You should use always use pnpm here since it's a pnpm monorepo. That's one of the first commands you see when looking at the [Getting Started](https://github.com/animavita/animavita/blob/v2/CONTRIBUTING.md#getting-started) section.
For now, you don't need to have any accounts. Neither AWS nor social accounts on Facebook. We're at the very beginning of the app restructuring so you should be ready to go without any of those accounts.

I'll update the docs clarifying that Linux or Mac is a requirement, thanks for that. 
But I believe if you start the setup from scratch using Linux or Mac and follow exactly what's in the guide, you should be able to get the app running without problems.

**Comment by belgamo** [comment]
Also, if you are interested in knowing more about the decisions we made to come up with the whole monorepo structure, here is a discussion https://github.com/animavita/animavita/issues/119 where I documented everything.
