### ISSUE TITLE
Setup authorization 

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#159]
depends on https://github.com/animavita/animavita/pull/135

**Comment by imbhaskarn** [comment]
Hey @belgamo I can help.

**Comment by belgamo** [comment]
Thanks @imbhaskarn 
I'll assign it to you but be aware that we still need to merge #135

**Comment by belgamo** [comment]
hey @imbhaskarn, #135 has been merged! Feel free to start working on it 😄

**Comment by belgamo** [comment]
Hey @imbhaskarn any updates on this?

**Comment by imbhaskarn** [comment]
Hey @belgamo I have created a pull request #168 . Im not sure if that's the correct way.
