### ISSUE TITLE
Replace mock objects with fakerjs

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#185]
https://fakerjs.dev/guide/usage.html

**Comment by brunohkbx** [comment]
Another suggestion: [fishery](https://github.com/thoughtbot/fishery) is pretty handy to set up factories

**Comment by Vedu1996** [comment]
I would like to pick this up :)

**Comment by Vedu1996** [comment]
Please have a look at https://github.com/animavita/animavita/pull/187, will make changes if required based on feedback
