### ISSUE TITLE
Add Signup screen

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#188]
depends on #200

## Task
We already have the `GetLocation` screen. Let's continue the work started on https://github.com/animavita/animavita/pull/181 by creating the `SignUp` screen and integrating these two pieces to complete the user onboarding.

Endpoint -> `POST /api/v1/auth/signUp`

## Requirements
- Add the SignUp screen
- Persist user credentials on AuthContext 
- After signing up, the user lands on the app home screen
- Handle network errors
- Add tests

**Comment by Isaac-alencar** [comment]
Since I already had worked in the previous issue, can I take that one too?

**Comment by belgamo** [comment]
> Since I already had worked in the previous issue, can I take that one too?

Sure!
