### ISSUE TITLE
Add my adoptions list screen

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#194]
## Task
Add a new screen where the owners can view their previously registered adoptions. Each card on this list should have edit and remove buttons. The link to the screen can be placed under the user profile which is accessible by touching the user's initials as shown below:

https://github.com/animavita/animavita/assets/19699724/4b6b5cf5-e206-4307-bd8e-4f52a991c808

**Endpoint** -> `GET api/v1/adoptions`

## Requirements
- Owner users see the adoptions that they created
- Fetches adoption from the backend
- Each adoption listed has remove and edit options
- Handle network errors
- Add tests

**Comment by tonyaraujop** [comment]
Hey there, can I git this one a try?

**Comment by Isaac-alencar** [comment]
hey, can I work on it? @belgamo

**Comment by belgamo** [comment]
Hi @Isaac-alencar, any updates here? Can I assign it to someone else?

**Comment by Isaac-alencar** [comment]
> Hi @Isaac-alencar, any updates here? Can I assign it to someone else?

Sorry, I did not have too much time lately to work on this issue, but I can deliver a PR by end of next week (at most). sounds good?

**Comment by belgamo** [comment]
> > Hi @Isaac-alencar, any updates here? Can I assign it to someone else?
> 
> Sorry, I did not have too much time lately to work on this issue, but I can deliver a PR by end of next week (at most). sounds good?

Sure, thanks!
