### ISSUE TITLE
Update sign up endpoint to return user's credentials

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#200]
## Task
Currently, when signing up, we return a successful string message. But it's not useful, so let's return the user's credentials so we can auto-sign the user in on the front-end side.

## Requirements
- Returns the user's tokens
- Update tests

**Comment by sivasuriyankumarasamy** [comment]
Hi @belgamo,
I would like to work on this.
Please assign this to me.

**Comment by sivasuriyankumarasamy** [comment]
Hi @belgamo ,

I am getting below error. 
```
JwtStrategy requires a secret or key
TypeError: JwtStrategy requires a secret or key
```

How can I get ? 
```
JWT_ACCESS_SECRET=
JWT_REFRESH_SECRET=
```

**Comment by belgamo** [comment]
> Hi @belgamo ,
> 
> I am getting below error. do I need to add any key?
> 
> `JwtStrategy requires a secret or key TypeError: JwtStrategy requires a secret or key`

Are you trying to run the app without docker? If so, please follow the [contribution guide](https://github.com/animavita/animavita/blob/v2/CONTRIBUTING.md#running-without-docker).

Basically, you have to set a secret in the `.env` file. If you're not familiar with that, you can also check [nest docs](https://docs.nestjs.com/security/authentication#jwt-token).

**Comment by sivasuriyankumarasamy** [comment]
Thanks @belgamo.

I figured it out.

**Comment by sivasuriyankumarasamy** [comment]
Hi @belgamo,

raised PR: https://github.com/animavita/animavita/pull/206
