### ISSUE TITLE
Get user location doesn't work on web

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#218]
## Issue
https://github.com/animavita/animavita/assets/19699724/a2769d25-72d9-4a4e-89ee-eff17bdf5926

## Context
Basically, on the web there's no way to reverse the user's latitude and longitude into an address "for free". We need to use [Places API](https://developers.google.com/maps/documentation/geocoding/requests-reverse-geocoding?hl=en) to achieve this and for that purpose, a Google API key is needed. So since this is an open-source project, every developer interested in contributing to and running this app on the web will have to have their own key and when we deploy this to a production environment I'll take care of the actual key.

## Task
I suggest we conditionally call the `Location.reverseGeocodeAsync` in this [hook](https://github.com/animavita/animavita/blob/v2/apps/mobile/src/hooks/use-user-location/use-user-location.ts#L43) meaning we will only call it if `Platform !== 'web'`. Then, for the web, we can consume the [geocoding service](https://developers.google.com/maps/documentation/geocoding/requests-reverse-geocoding?hl=en).

## Requirements
- User can use the app on the web
- Update .env file to include `GOOGLE_API_KEY`

**Notes to myself:**
- Remember to [restrict the API key](https://cloud.google.com/blog/products/maps-platform/google-maps-platform-best-practices-restricting-api-keys)

## References
https://docs.expo.dev/versions/latest/sdk/location/#locationreversegeocodeasynclocation-options
https://stefma.medium.com/something-about-google-api-keys-how-to-secure-them-and-what-firebase-got-to-do-with-this-e10473637ed3

**Comment by Therocking** [comment]
Is this issues open yet?

**Comment by belgamo** [comment]
> Is this issues open yet?

yep, do you want to pick it up?

**Comment by Therocking** [comment]
I can try to fix it. Tell me about this problem, where is the component?

**Comment by belgamo** [comment]
> I can try to fix it. Tell me about this problem, where is the component?

I don't have too much context on this, that's why I labeled this issue with "needs investigation". Overall it's working perfectly on mobile but is failing on web with that warning I showed in the video. It's gonna require you some research around the [`expo-location`](https://docs.expo.dev/versions/latest/sdk/location/) to understand why it's not working on web. In theory, it should work cause on expo docs it says it support all platforms but in case you can't get working at all, then we're gonna have to develop a web version of the `user-user-location` hook.

https://docs.expo.dev/versions/latest/sdk/location/

**Comment by belgamo** [comment]
Looks like that's the problem https://docs.expo.dev/versions/latest/sdk/location/#locationreversegeocodeasynclocation-options

**Comment by Therocking** [comment]
right, I'm going to read the doc and try to fix it

**Comment by belgamo** [comment]
> right, I'm going to read the doc and try to fix it

Honestly it doesn't seem to be a bug, we just need to understand what that warning means and then come up with a solution.

**Comment by Therocking** [comment]
From what you can see is a dependency error. Say it is deprecate and removed.

**Comment by belgamo** [comment]
> From what you can see is a dependency error. Say it is deprecate and removed.

Ok, here's the thing: basically on the web there's no way to reverse the user's latitude and longitude into an address "for free". We need to use [Places API](https://developers.google.com/maps/documentation/geocoding/requests-reverse-geocoding?hl=en) to achieve this and for that purpose, an Google API key is needed. So basically since this is an open-source project, every developer interested in contributing and running this app on the web will have to have their own key and when we deploy this to a production environment I'll take care of the actual key. Does it make sense?

I've updated the issue description with the requirements, lemme me know if you're still interested in working on it.

**Comment by RafaelAllves** [comment]
I'm interested in this issue and would like to contribute to its resolution. Before diving in, I'd like to know if someone is already assigned to it or if it's available for me to start working on.

My proposal to address this issue would be to replace the current location service with [Leaflet](https://leafletjs.com/). I believe this change would be advantageous because Leaflet offers a generous free tier, and obtaining an API key is simpler, requiring no payment method registration.

**Comment by RafaelAllves** [comment]
I'm interested in this issue and would like to contribute to its resolution. Before diving in, I'd like to know if someone is already assigned to it or if it's available for me to start working on.

My proposal to address this issue would be to investigate the potential replacement of the current reverse geocoding service with [OpenCageData](https://opencagedata.com/). I believe this change would be advantageous because OpenCageData offers a generous free tier (2,500 requests/day), as well as simplifying the API key acquisition process, without requiring payment method registration. As an alternative, I suggest that if using the service isn't feasible, there could be an option to select country, state, and city using selectors.

**Comment by belgamo** [comment]
> I'm interested in this issue and would like to contribute to its resolution. Before diving in, I'd like to know if someone is already assigned to it or if it's available for me to start working on.
> 
> My proposal to address this issue would be to investigate the potential replacement of the current reverse geocoding service with [OpenCageData](https://opencagedata.com/). I believe this change would be advantageous because OpenCageData offers a generous free tier (2,500 requests/day), as well as simplifying the API key acquisition process, without requiring payment method registration. As an alternative, I suggest that if using the service isn't feasible, there could be an option to select country, state, and city using selectors.

loved the idea, sounds like a plan! please, take over this issue.

**Comment by RafaelAllves** [comment]
@belgamo, I believe I've resolved the issue with the solution I proposed earlier. I tried to make minimal changes and maintain the existing code and architecture standards. Additionally, I updated the CONTRIBUTING.md file to reflect the changes made. Feel free to modify anything you deem necessary.

![image](https://github.com/animavita/animavita/assets/60854016/b65351aa-9661-421e-a7e1-d5bdf9fb9278)

**Comment by RafaelAllves** [comment]
@belgamo, I believe I've resolved the issue with the solution I proposed earlier. I tried to make minimal changes and maintain the existing code and architecture standards. Additionally, I updated the CONTRIBUTING.md file to reflect the changes made. You can find more details in the corresponding pull request #227. Feel free to review and provide any feedback. 


![image](https://github.com/animavita/animavita/assets/60854016/7af92a00-5bb5-47d4-8327-4854c721e5f1)
