### ISSUE TITLE
Authentication with Google Account

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#35]

**Comment by renanmav** [comment]
We can use the new service of auth written by @evanbacon

**Comment by renanmav** [comment]
Check this https://twitter.com/Baconbrix/status/1256985914749759488

**Comment by wm4tos** [comment]
Will be used the service maded for @EvanBacon? I need to know because I want to code this feature.

**Comment by joaoGabriel55** [comment]
I can do this task @belgamo
