### ISSUE TITLE
Persist user language preferences

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#80]
As we've implemented the i18n resource on this project, we want the users to be able to choose the app language.

- [ ] Build the user preference screen
- [ ] Add mutation to persist the user preferences
- [ ] Add query to return the user preferences

**Comment by ImperadorSid** [comment]
@belgamo, could you assign this issue to me?

**Comment by belgamo** [comment]
> @belgamo, could you assign this issue to me?

Sure!
