### ISSUE TITLE
S3 objects aren't appering on android

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#87]
### Problem
After #84 the images stopped appering on android. That happens only when we run graphql package in docker. So, I suppose the app are trying to get the images with "localhost" in URL which doesn't work on Android. Probably because when using docker, we mock all AWS dependencies locally such as S3 that no longer stores a public object URL which was accesible to both (android/ios) in the past.

### Proposed solution
I think changing URL of S3 objects to points to `10.0.2.2` will fix this problem.

To testing, the user picture must appear in the header.
![image](https://user-images.githubusercontent.com/19699724/118853918-ac52f100-b8aa-11eb-9038-ed7859424695.png)

### Reference
https://developer.android.com/studio/run/emulator-networking

**Comment by efgalvao** [comment]
Hello !
Can you assign this one to me ?
