### ISSUE TITLE
Fix dropdown menu on web

### ISSUE THREAD

**Issue by belgamo** [wendelfreitas/animavita#90]
### Problem
On web, the dropdown menu #71 doesn't work when clicking on profile picture.

### Screenshots
![Screen Shot 2021-05-24 at 02 33 29](https://user-images.githubusercontent.com/19699724/119301171-701be980-bc38-11eb-8a96-47814521aca6.png)

**Comment by Beigelman** [comment]
Assign this issue for me, please @belgamo

**Comment by efgalvao** [comment]
@Beigelman , did you fixed this one ? ?

**Comment by Beigelman** [comment]
@efgalvao no I didn't. I'm more focused on the back end right now. You can grab this ticket if you want

**Comment by efgalvao** [comment]
@belgamo , I would like to try fix this one.
